/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sig.view;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sig.control.InvActionListeners;
import sig.control.SelectListeners;
import sig.model.InvHeaderTableModel;
import sig.model.InvLineTableModel;
import sig.model.InvoiceHeader;
import sig.model.InvoiceLine;
/**
 *
 * @author AyetAllah
 */
public class SigFrame extends javax.swing.JFrame  {

    /**
     * Creates new form SigFrame
     */
    public SigFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SP_invoice_headers = new javax.swing.JScrollPane();
        Table_invoices = new javax.swing.JTable();
        BT_create_invoice = new javax.swing.JButton();
        BT_delete_invoice = new javax.swing.JButton();
        Panel_invoice_header = new javax.swing.JPanel();
        Label_inv_id = new javax.swing.JLabel();
        Label_inv_id2 = new javax.swing.JLabel();
        Label_inv_date2 = new javax.swing.JLabel();
        Label_inv_date = new javax.swing.JLabel();
        Label_cust_name2 = new javax.swing.JLabel();
        Label_cust_name = new javax.swing.JLabel();
        Label_total_invoice = new javax.swing.JLabel();
        Label_total_invoice2 = new javax.swing.JLabel();
        SP_invoice_lines = new javax.swing.JScrollPane();
        Table_Invoice_lines = new javax.swing.JTable();
        Label_invoice_details = new javax.swing.JLabel();
        BT_NewLine = new javax.swing.JButton();
        BT_delete_line = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        MI_load_item = new javax.swing.JMenuItem();
        MI_load_item.addActionListener(Listener_handler);

        MI_save_file = new javax.swing.JMenuItem();
        MI_save_file.addActionListener(Listener_handler);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Invoice Generator");

        Table_invoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table_invoices.setToolTipText("");
        Table_invoices.getSelectionModel().addListSelectionListener(selectlistener);
        SP_invoice_headers.setViewportView(Table_invoices);

        BT_create_invoice.setText("Create Invoice");
        BT_create_invoice.addActionListener(Listener_handler);

        BT_delete_invoice.setText("Delete Invoice");
        BT_delete_invoice.addActionListener(Listener_handler);
        BT_delete_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_delete_invoiceActionPerformed(evt);
            }
        });

        Label_inv_id.setText("Invoice Number");

        Label_inv_date.setText("Invoice Date");

        Label_cust_name.setText("Customer Name");

        Label_total_invoice.setText("Invoice Total");

        Table_Invoice_lines.getSelectionModel().addListSelectionListener(selectlistener
        );
        SP_invoice_lines.setViewportView(Table_Invoice_lines);

        Label_invoice_details.setText("Invoice Items");

        javax.swing.GroupLayout Panel_invoice_headerLayout = new javax.swing.GroupLayout(Panel_invoice_header);
        Panel_invoice_header.setLayout(Panel_invoice_headerLayout);
        Panel_invoice_headerLayout.setHorizontalGroup(
            Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_invoice_headerLayout.createSequentialGroup()
                .addComponent(SP_invoice_lines, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(Panel_invoice_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_invoice_details)
                    .addGroup(Panel_invoice_headerLayout.createSequentialGroup()
                        .addGroup(Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Label_cust_name)
                                .addComponent(Label_inv_id, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(Label_total_invoice)
                            .addComponent(Label_inv_date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_inv_date2)
                            .addComponent(Label_inv_id2)
                            .addComponent(Label_total_invoice2)
                            .addComponent(Label_cust_name2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_invoice_headerLayout.setVerticalGroup(
            Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_invoice_headerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_inv_id2)
                    .addComponent(Label_inv_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_inv_date2)
                    .addComponent(Label_inv_date, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_cust_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_invoice_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_total_invoice)
                    .addComponent(Label_total_invoice2))
                .addGap(35, 35, 35)
                .addComponent(Label_invoice_details)
                .addGap(36, 36, 36)
                .addComponent(SP_invoice_lines, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        BT_NewLine.setText("New Line");
        BT_NewLine.addActionListener(Listener_handler);

        BT_delete_line.setText("Delete Line");
        BT_delete_line.setActionCommand("delete_line");
        BT_delete_line.addActionListener(Listener_handler);

        File.setText("File");

        MI_load_item.setText("Load File");
        MI_load_item.setAutoscrolls(true);
        File.add(MI_load_item);

        MI_save_file.setText("Save File");
        MI_save_file.setAutoscrolls(true);
        File.add(MI_save_file);

        jMenuBar1.add(File);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_create_invoice)
                        .addGap(48, 48, 48)
                        .addComponent(BT_delete_invoice))
                    .addComponent(SP_invoice_headers, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(BT_NewLine)
                        .addGap(52, 52, 52)
                        .addComponent(BT_delete_line))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Panel_invoice_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SP_invoice_headers)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_invoice_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_create_invoice)
                    .addComponent(BT_delete_invoice)
                    .addComponent(BT_NewLine)
                    .addComponent(BT_delete_line))
                .addGap(25, 25, 25))
        );

        setBounds(0, 0, 836, 799);
    }// </editor-fold>//GEN-END:initComponents

    private void BT_delete_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_delete_invoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_delete_invoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SigFrame().setVisible(true);
            }
        });
        
        
       
    }

 
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_NewLine;
    private javax.swing.JButton BT_create_invoice;
    private javax.swing.JButton BT_delete_invoice;
    private javax.swing.JButton BT_delete_line;
    private javax.swing.JMenu File;
    private javax.swing.JLabel Label_cust_name;
    private javax.swing.JLabel Label_cust_name2;
    private javax.swing.JLabel Label_inv_date;
    private javax.swing.JLabel Label_inv_date2;
    private javax.swing.JLabel Label_inv_id;
    private javax.swing.JLabel Label_inv_id2;
    private javax.swing.JLabel Label_invoice_details;
    private javax.swing.JLabel Label_total_invoice;
    private javax.swing.JLabel Label_total_invoice2;
    private javax.swing.JMenuItem MI_load_item;
    private javax.swing.JMenuItem MI_save_file;
    private javax.swing.JPanel Panel_invoice_header;
    private javax.swing.JScrollPane SP_invoice_headers;
    private javax.swing.JScrollPane SP_invoice_lines;
    private javax.swing.JTable Table_Invoice_lines;
    private javax.swing.JTable Table_invoices;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

 DateFormat df =new  SimpleDateFormat("dd-MM-yyyy");
    
    private InvActionListeners Listener_handler= new InvActionListeners(this);
    private ArrayList<InvoiceHeader> Headers/* =new ArrayList<>()*/;
    private ArrayList<InvoiceLine> Lines;
    private InvHeaderTableModel htmodel;
    private InvLineTableModel Ltmodel;
    private SelectListeners selectlistener =new SelectListeners(this);
     //private SelectListeners selectlistenerline =new SelectListeners(this);
    //private NewHeaderDialog invdialog= new NewHeaderDialog(this);
    
    // Table_invoices.getSelectionModel().addListSelectionListener(selectlistener);

  /*  public NewHeaderDialog getInvdialog() {
        return invdialog;
    }

    public void setInvdialog(NewHeaderDialog invdialog) {
        this.invdialog = invdialog;
    }*/

    
    public void setHeaders(ArrayList<InvoiceHeader> arr){
        /*
        if(arr==null)
        {
            arr=new ArrayList<InvoiceHeader>();
            return;
        }*/
        this.Headers=arr;
    }
     public ArrayList<InvoiceHeader> getHeaders(){
        if(Headers==null)
            return new ArrayList<InvoiceHeader>();
        return Headers;
    }
     
      public void setLines(ArrayList<InvoiceLine> arr){
        
        this.Lines=arr;
    }
     public ArrayList<InvoiceLine> getLines(){
        
        return(this.Lines);
    }

    public JTable getTable_Invoice_lines() {
        /*if(Table_Invoice_lines==null)
        {
            Table_Invoice_lines =new  javax.swing.JTable();
        }*/
        return Table_Invoice_lines;
    }
 public void setHtmodel(InvHeaderTableModel htmodel) {
        this.htmodel = htmodel;
    }

    public InvHeaderTableModel getHtmodel() {
        return htmodel;
    }

    public InvLineTableModel getLtmodel() {
        return Ltmodel;
    }
 
 
 public void setLtmodel(InvLineTableModel Ltmodel) {
        this.Ltmodel = Ltmodel;
    }
    public JTable getTable_invoices() {
        return Table_invoices;
    }

     public InvoiceHeader getObject(int code)
    {
        InvoiceHeader h=new InvoiceHeader();
        for( InvoiceHeader header : Headers)
        {
            if(header.getID()==code)
            {
               h=header ;
            }          
        }
        return h;
     }

    public JLabel getLabel_cust_name() {
        return Label_cust_name2;
    }

    public JLabel getLabel_inv_date() {
        return Label_inv_date2;
    }

    public InvActionListeners getListener_handler() {
        return Listener_handler;
    }

    public JLabel getLabel_inv_id() {
        return Label_inv_id2;
    }

    public JLabel getLabel_total_invoice() {
        return Label_total_invoice2;
    }
     
     

}
    

